{% set name = "Mixture-Models" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Mixture_Models-{{ version }}.tar.gz
  sha256: 23605474b22f93bafc2b70455c9276eaa185dca8086d7b47f46854e3cacbeca6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6,<=3.10
    - pip
  run:
    - python >=3.6,<=3.10
    - autograd ==1.3
    - future >=0.18.2
    - matplotlib-base >=3.5.1
    - numpy >=1.21.0,<1.24
    - scikit-learn >=0.24.1
    - scipy >=1.7.0

test:
  imports:
    - Mixture_Models
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python library for fitting mixture models using gradient based inference
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - santhosh-kasa
